---
title: "Lab Week 8"
author: "Emma Siegfried"
date: "March 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load Packages
```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
```

###Column graph of TX oil spills
```{r, message=FALSE}

oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x=Year, y=Loss))+
  geom_col()+
  theme_classic()

```

###Leaflet plot of spill locations in TX in 2016
```{r}

df_loc <- oil_spills %>% 
  filter(`Accident State` == 'TX' & `Accident Year`== 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

#Have R recognize this data as spatial info

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326) #now R knows it's spatial

class(oil_sf) #the first thing is "sf", meaning spatial features

```

```{r map}

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()


```

##tmap plot with the Texas state shapefile
```{r}

states <- st_read(dsn = ".", layer = "states") #the dsn="." tells it to get everything from the working directory that meets the "layer" requirement

tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326) #this ensures the spatial data will use the same coordinates as all the other files

plot(tex_border)

tm_shape(tex_border)+
  tm_polygons()+
  tm_shape(oil_sf)+
  tm_dots(size = 0.3)


```

###Convert the data to spatial points patterns (combination of point data and the bounding window)

```{r}
#We need to convert to point pattern data with a window

#1) convert back from simple features to dataframes

spill_sp <- as(oil_sf, "Spatial")

spill_ppp <- as(spill_sp, "ppp") #ppp stands for point pattern

class(spill_ppp) #it is now ppp

tx_sp <- as(tex_border, "Spatial")

tx_owin <- as(tx_sp, "owin") 

#Now we will combine

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)


```



















